name: "Werid Blog"
type: "python:3.13"

relationships:
  database: "db:postgresql"

web:
  upstream:
    socket_family: unix
  commands:
    start: "gunicorn -w 4 -b unix:$SOCKET wb_project.wsgi:application"
  locations:
    "/":
      passthru: true
    "/static":
      root: "static"
      expires: 1h
      allow: true

disk: 512

# set a local read/ write mount for logs
mounts:
  "logs":
    source: local
    source_path: logs

# The hooks executed at the various points in the lifecycle of the application.

hooks:
  build: |
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirements_remote.txt

    mkdir logs
    python manage.py collectstatic
    rm -rf logs

  deploy: |
    python manage.py migrate
