name: "weird_blog"
type: "python:3.13"

relationships:
  database: "db:mysql"

web:
  upstream:
    socket_family: unix
  commands:
    start: "gunicorn -w 4 -b unix:$SOCKET wb_project.wsgi:application"
  locations:
    "/":
      passthru: true
    "/static":
      root: "staticfiles"
      expires: 1h
      allow: true

disk: 512

mounts:
  "logs":
    source: local
    source_path: logs
  "sessions":
    source: local
    source_path: sessions

hooks:
  build: |
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirements_remote.txt
    python manage.py collectstatic --noinput

  deploy: |
    python manage.py migrate
