"""
Django settings for wb_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information, see:
https://docs.djangoproject.com/en/5.2/topics/settings/
"""


from pathlib import Path
from platformshconfig import Config
from urllib.parse import urlparse
import os

# Base directory (same as BASE_DIR)
BASE_DIR = Path(__file__).resolve().parent.parent

# Platform.sh Config
config = Config()

# SECURITY
SECRET_KEY = 'django-insecure-you-should-generate-your-own-key'

DEBUG = True  # overridden by Platform.sh config below

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = []

# Override settings for Platform.sh
if config.is_valid_platform():

    # Set ALLOWED_HOSTS from active routes
    if not config.in_build():
        try:
            domains = [urlparse(url).hostname for url in config.routes().keys()]
            ALLOWED_HOSTS += domains
            CSRF_TRUSTED_ORIGINS = [f"https://{domain}" for domain in domains]
        except Exception:
            pass

    # Disable debug and set secret key from entropy
    DEBUG = False

    # Use project_entropy if it exists, otherwise keep the existing SECRET_KEY
    SECRET_KEY = getattr(config, "project_entropy", SECRET_KEY)

# Application definition
INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your Apps
    'weird_blog',
    'accounts',

    # Third-Party Apps
    'django_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wb_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # Customize if needed
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wb_project.wsgi.application'

# Database: Use SQLite by default, override on Platform.sh
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Handle Platform.sh DB
if config.is_valid_platform() and not config.in_build():
    creds = config.credentials('database')
    DATABASES['default'] = {
        'ENGINE': f"django.db.backends.{creds['scheme']}",
        'NAME': creds['path'],
        'USER': creds['username'],
        'PASSWORD': creds['password'],
        'HOST': creds['host'],
        'PORT': creds['port'],
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default auto key field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom settings
LOGIN_REDIRECT_URL = 'weird_blog:index'
LOGOUT_REDIRECT_URL = 'weird_blog:index'
LOGIN_URL = 'accounts:login'

SESSION_ENGINE = 'django.contrib.sessions.backends.file'
SESSION_FILE_PATH = os.path.join(BASE_DIR, 'sessions')
